# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/102Qd9sP9n55OCDuaZiRok0BZPL7wsRtq
"""

import time
import timeit
import random
import numpy as np
import sys
from matplotlib import pyplot as plt
from scipy.linalg import lu_factor, lu_solve
from scipy.linalg import ldl, solve_triangular, cholesky, lu_factor, lu_solve

#Compute the step size for the Newton method to ensure feasibility of Lagrange multipliers and slack variables.

    #Parameters
    #lamb0: Current values of Lagrange multipliers
    #lamb1: changes to the Lagrange multipliers
    #s0: Current values of slack variables
    #ds:  changes to the slack variables


def Newton_step(lamb0, lamb1, s0, ds):

    alpha = 1
    index_lamb0 = np.array(np.where(lamb1 < 0))

    if index_lamb0.size > 0:

        alpha = min(alpha,np.min(-lamb0[index_lamb0]/lamb1[index_lamb0]))
    index_s0 = np.array(np.where(ds<0))

    if index_s0.size > 0:

        alpha = min(alpha, np.min(-s0[index_s0]/ds[index_s0]))

    return alpha


def Matrix_KKT(G, C, n, m, lamb, s):


    #Parameters
    #G : Coefficients for the quadratic objective function.
    #C : Constraint matrix.
    #n : Number of variables.
    #m  Number of constraints.
    #lamb : Lagrange multipliers.
    #s : Slack variables.

    S = np.diag(s)
    Lambdas = np.diag(lamb)
    eq1 = np.concatenate((G, -C, np.zeros((n, m))), axis = 1)
    eq2 = np.concatenate((np.transpose(-C), np.zeros((m, m)), np.identity(m)), axis = 1)
    eq3 = np.concatenate((np.zeros((m, n)), S, Lambdas), axis = 1)
    Mat = np.concatenate((eq1, eq2, eq3))

    #Returning Variables:
    #The KKT matrix.
    #The diagonal matrix of slack variables (S).
    #The diagonal matrix of Lagrange multipliers (Lambdas)

    return Mat, S, Lambdas

def F(x, G, g):

    #The return value is the value of the objective function.
    return 0.5 * np.transpose(x).dot(G).dot(x) + np.transpose(g).dot(x)


def F_z(x,lamb,s, G, g, C, d):

    equasion1 = G.dot(x) + g - C.dot(lamb)
    equasion2 = s + d - np.transpose(C).dot(x)
    equasion3 = s * lamb

    #Return value is a vector of equations for the KKT conditions.
    return np.concatenate((equasion1, equasion2, equasion3))


def Program_for_C2(n, maxIter=100, epsilon=10e-16):

  #Parameters
  #n: The number of variables in the optimization problem
  #maxIter: The maximum number of iterations allowed for the algorithm
  #epsilon: Threshold for convergence
  #Print_Time: Option to print computation time
  #Print_Results: Option to print optimization results

    #random number generation
    np.random.seed(2)
    random.seed(2)

    #Initialize our variables
    m = 2*n  # m is twice as the number of variables
    x = np.zeros((n)) # initial decision variables zero vector
    lamb = np.ones((m)) # lagrange multiplier vector
    s = np.ones((m)) # slack variables
    z = np.concatenate((x, lamb, s)) # vector of z
    G = np.identity(n)       # G is the identity matrxi for the objective function
    C = np.concatenate((G, - G), axis = 1) # inequality constrains
    d = np.full((m), - 10)
    e = np.ones((m))
    g = np.random.normal(0, 1, (n))

    Mat, S, Lambdas = Matrix_KKT(G, C, n, m, lamb,s)

    for i in range(maxIter):


        #The KKT conditions are evaluated, and the system is solved for the update vector delta.
        b = -F_z(x, lamb, s, G, g, C, d)
        delta = np.linalg.solve(Mat,b)

        #Get the value for alpha using predefined Newton step
        alpha = Newton_step(lamb, delta[n:n+m], s, delta[n+m:])

        # Step Size Adjustment
        mu = s.dot(lamb) / m
        Mu = ((s + alpha * delta[n+m:]).dot(lamb + alpha * delta[n:(n + m)])) / m
        sigma = (Mu/mu)**3

        # Correcting sub-step
        b[(n + m):] = b[(n + m):] - np.diag(delta[(n + m):]*delta[n:(n + m)]).dot(e) + sigma * mu * e

        # We get delta by using the linalg function
        delta = np.linalg.solve(Mat, b)

        #  Step-size correction with delta
        alpha = Newton_step(lamb, delta[n:(n + m)], s, delta[(n + m):])

        # update the sub-step
        z = z + (alpha * delta) * 0.95

        # Define the Stopping citeria for Convergence
        if (np.linalg.norm(-b[:n]) < epsilon) or (np.linalg.norm(-b[n:(n + m)]) < epsilon) or (np.abs(mu) < epsilon):
            break

        # Update our variables for next iteration
        x = z[:n]
        lamb = z[n:(n + m)]
        s = z[(n + m):]
        Mat, S, Lambdas = Matrix_KKT(G, C, n, m, lamb, s)

    print('Minimum from  the function:', F(x, G, g))
    print('Real minimum is:', F(-g, G, g))
    print('Iterations:', i)
    print('Condition number:', np.linalg.cond(Mat))

    return(i, abs(F(x, G, g) - F(-g, G, g)), np.linalg.cond(Mat))

result = Program_for_C2(n=10)

def Program_for_C3(n, maxIter=100, epsilon=10e-16, Print_Time = "Yes", Print_Results = "Yes"):

  #Parameters
  #n: The number of variables in the optimization problem
  #maxIter: The maximum number of iterations allowed for the algorithm
  #epsilon: Threshold for convergence
  #Print_Time: Option to print computation time
  #Print_Results: Option to print optimization results

    #random number generation
    np.random.seed(2)
    random.seed(2)

    #Initialize our variables
    m = 2*n  # m is twice as the number of variables
    x = np.zeros((n)) # initial decision variables zero vector
    lamb = np.ones((m)) # lagrange multiplier vector
    s = np.ones((m)) # slack variables
    z = np.concatenate((x, lamb, s)) # vector of z
    G = np.identity(n)       # G is the identity matrxi for the objective function
    C = np.concatenate((G, - G), axis = 1) # inequality constrains
    d = np.full((m), - 10)
    e = np.ones((m))
    g = np.random.normal(0, 1, (n))

    # Count executiuon time
    Start = time.time()

    Mat, S, Lambdas = Matrix_KKT(G, C, n, m, lamb,s)

    for i in range(maxIter):


        #The KKT conditions are evaluated, and the system is solved for the update vector delta.
        b = -F_z(x, lamb, s, G, g, C, d)
        delta = np.linalg.solve(Mat,b)

        #Get the value for alpha using predefined Newton step
        alpha = Newton_step(lamb, delta[n:n+m], s, delta[n+m:])

        # Step Size Adjustment
        mu = s.dot(lamb) / m
        Mu = ((s + alpha * delta[n+m:]).dot(lamb + alpha * delta[n:(n + m)])) / m
        sigma = (Mu/mu)**3

        # Correcting sub-step
        b[(n + m):] = b[(n + m):] - np.diag(delta[(n + m):]*delta[n:(n + m)]).dot(e) + sigma * mu * e

        # We get delta by using the linalg function
        delta = np.linalg.solve(Mat, b)

        #  Step-size correction with delta
        alpha = Newton_step(lamb, delta[n:(n + m)], s, delta[(n + m):])

        # update the sub-step
        z = z + (alpha * delta) * 0.95

        # Define the Stopping citeria for Convergence
        if (np.linalg.norm(-b[:n]) < epsilon) or (np.linalg.norm(-b[n:(n + m)]) < epsilon) or (np.abs(mu) < epsilon):

            break

        # Update our variables for next iteration
        x = z[:n]
        lamb = z[n:(n + m)]
        s = z[(n + m):]
        Mat, S, Lambdas = Matrix_KKT(G, C, n, m, lamb, s)

    #Show results


    End = time.time()



    print("Computational time needed =  ", End - Start)
    print('Minimum from  the function:', F(x, G, g))
    print('Real minimum is:', F(-g, G, g))
    print('Iterations:', i)
    print('Condition number:', np.linalg.cond(Mat))

    return(End - Start, i, abs(F(x, G, g) - F(-g, G, g)), np.linalg.cond(Mat))


# Call the function:
result = Program_for_C3(n=10)


# We create the KKT Matrix, lambda and S matrices.

def M_KKT_1(G, C, lamb, s):

    S = np.diag(s)
    Lambdas = np.diag(lamb)
    eq1 = np.concatenate((G, -C),axis = 1)
    eq2 = np.concatenate((- np.transpose(C), - np.diag(1 / lamb * s)), axis = 1)
    Mat = np.concatenate((eq1, eq2))

    return Mat, S, Lambdas

def Func_C4_strategy_1(n, maxIter=100, epsilon=10e-16, Print_Time = "Yes", Print_Results = "No"):

    # Set the seed for random number generation
    np.random.seed(2)
    # Set the seed for the random module
    random.seed(2)

    # Parameters
    m = 2*n
    x = np.zeros((n))
    lamb = np.ones((m))
    s = np.ones((m))
    z = np.concatenate((x,lamb,s))
    G = np.identity(n)
    C = np.concatenate((G,-G),axis = 1)
    d = np.full((m), -10)
    e = np.ones((m))
    g = np.random.normal(0, 1, (n))


    # Start count time
    if Print_Time == "Yes":
        np.random.seed(4)
        Start = time.time()

    # Get the values using the function

    Mat, S, Lambda = M_KKT_1(G, C, lamb, s)

    for i in range(maxIter):

        lamb_inv = np.diag(1/lamb)

        b = F_z(x, lamb, s, G, g, C, d)
        r1 = b[:n]
        r2 = b[n:(n + m)]
        r3 = b[(n + m):]
        b = np.concatenate(([- r1, - r2 + 1/ lamb * r3]))

        # Now i will apply the LDL factorization
        L, D, perm = ldl(Mat)
        y = solve_triangular(L, b, lower=True, unit_diagonal = True)
        delta = solve_triangular(D.dot(np.transpose(L)), y, lower = False)
        deltaS = lamb_inv.dot(- r3 - s * delta[n:])
        delta = np.concatenate((delta, deltaS))

        # step-size correction function from before
        alpha = Newton_step(lamb, delta[n:(n + m)], s, delta[(n + m):])

        # We compute the adjusted param
        mu = s.dot(lamb) / m
        Mu = ((s + alpha * delta[(n + m):]).dot(lamb + alpha * delta[n:(n + m)])) / m
        sigma = (Mu / mu) ** 3

        #  substep
        Ds = np.diag(delta[(n + m):] * delta[n:(n + m)])
        b = np.concatenate((-r1, -r2 + lamb_inv.dot(r3 + Ds.dot(e) - sigma * mu * e)))

        # Repeat the LDL factorization
        y = solve_triangular(L, b, lower = True, unit_diagonal = True)
        delta = solve_triangular(D.dot(np.transpose(L)), y, lower = False)
        deltaS = lamb_inv.dot(-r3 - Ds.dot(e) + sigma * mu * e - s * delta[n:])
        delta = np.concatenate((delta, deltaS))

        # Step-size adjust substep
        alpha = Newton_step(lamb, delta[n:(n + m)], s, delta[(n + m):])

        z = z + (alpha * delta) * 0.95

        # Stopping citeria
        if (np.linalg.norm(- b[:n]) < epsilon) or (np.linalg.norm(- b[n:(n + m)]) < epsilon) or (np.abs(mu) < epsilon):
            break

        # Update the Matrix_KKT
        x = z[:n]
        lamb = z[n:(n + m)]
        s = z[(n + m):]
        Mat, S, Lambda = M_KKT_1(G, C, lamb, s)


    if Print_Time == "Yes":

        End = time.time()

        if Print_Results == "Yes":

            print("The computational time for the test problem is equal to: ", End - Start)

    if Print_Results == "Yes":

        print('Minimum from  the function:', F(x, G, g))
        print('Real minimum :', F(-g, G, g))
        print('Iterations:', i)
        print('Condition number:', np.linalg.cond(Mat))

    return(End - Start, i, abs(F(x, G, g) - F(-g, G, g)), np.linalg.cond(Mat))


#Function to compute the table, S, Lambdas
def M_KKT_2(G, C, lamb, s):

    S = np.diag(s)
    Lambdas = np.diag(lamb)
    Mat = G + C.dot(np.diag(1 / s * lamb)).dot(np.transpose(C))

    return Mat, Lambdas, S

def Func_C4_strategy_2(n, maxIter=100, epsilon=10e-16, Print_Time = "Yes", Print_Results = "No"):
    np.random.seed(2)
    random.seed(2)

    # Parameters
    m = 2 * n
    x = np.zeros((n))
    lamb = np.ones((m))
    s = np.ones((m))
    z = np.concatenate((x, lamb, s))
    G = np.identity(n)
    C = np.concatenate((G, - G),axis = 1)
    d = np.full((m), - 10)
    e = np.ones((m))
    g = np.random.normal(0, 1, (n))

    # Start to count time
    if Print_Time == "Yes":
        np.random.seed(4)
        Start = time.time()

    #Get the values from the function above
    Ghat, Lambda, S  = M_KKT_2(G, C, lamb,s)

    for i in range(maxIter):

        S_inv = np.diag(1 / s)
        b = F_z(x, lamb, s, G, g, C, d)
        r1 = b[:n]
        r2 = b[n:(n + m)]
        r3 = b[(n + m):]
        rhat = - C.dot(np.diag(1 / s)).dot((- r3 + lamb * r2))
        b = - r1 - rhat

        # Now i do the Cholesky factorization
        Cholesk = cholesky(Ghat, lower = True)
        y = solve_triangular(Cholesk, b, lower=True)
        delta_x = solve_triangular(np.transpose(Cholesk), y)
        delta_lamb = S_inv.dot((- r3 + lamb * r2)) - S_inv.dot(Lambda.dot(np.transpose(C)).dot(delta_x))
        delta_s = - r2 + np.transpose(C).dot(delta_x)
        delta = np.concatenate((delta_x,delta_lamb, delta_s))


        alpha = Newton_step(lamb, delta[n:(n + m)], s, delta[(n + m):])

        # Computing the adjusted paramameters
        mu = s.dot(lamb) / m
        Mu = ((s + alpha * delta[(n + m):]).dot(lamb + alpha * delta[n:(n + m)])) / m
        sigma = (Mu / mu) ** 3

        # substep
        Ds_Dlamb = np.diag(delta[n+m:]*delta[n:n+m])
        b = -r1-(-C.dot(np.diag(1/s)).dot((-r3-Ds_Dlamb.dot(e)+sigma*mu*e+lamb*r2)))

        # Do the Cholesky factorization second time
        y = solve_triangular(Cholesk,b,lower=True)
        delta_x = solve_triangular(np.transpose(Cholesk),y)
        delta_lamb = S_inv.dot(-r3-Ds_Dlamb.dot(e)+sigma*mu*e+lamb*r2)-S_inv.dot(lamb*(np.transpose(C).dot(delta_x)))
        delta_s = - r2 + np.transpose(C).dot(delta_x)
        delta = np.concatenate((delta_x,delta_lamb, delta_s))

        # Step-size adjust substep
        alpha = Newton_step(lamb, delta[n:(n + m)],s,delta[(n + m):])

        z = z + (alpha * delta) * 0.95

        # Stopping citeria
        if (np.linalg.norm(- r1) < epsilon) or (np.linalg.norm(-r2) < epsilon) or (np.abs(mu) < epsilon):

            break

        # Update the Matrix_KKT
        x = z[:n]
        lamb = z[n:(n + m)]
        s = z[(n + m):]
        Ghat, Lambda, S = M_KKT_2(G, C, lamb,s)

    if Print_Time == "Yes":

        End = time.time()

        if Print_Results == "Yes":

            print("Computation time for the test problem: ", End - Start)

    if Print_Results == "Yes":
        print('Minimum from  the function:', F(x, G, g))
        print('Real minimum :', F(-g, G, g))
        print('Iterations:', i)
        print('Condition number:', np.linalg.cond(Ghat))

    return(End - Start, i, abs(F(x, G, g) - F(-g, G, g)), np.linalg.cond(Ghat))

#Call the function
print('Using Stradegy 1 Results\n')
Func_C4_strategy_1(n=10, maxIter=100, epsilon=10e-16, Print_Time = "Yes", Print_Results = "Yes")
print('\n\nUsing Stradegy 2 Results\n')
Func_C4_strategy_2(n = 10, Print_Time = "Yes", Print_Results = "Yes")


print("N = 10 ")

print("C3")
Program_for_C3(n=10, Print_Time="Yes", Print_Results="Yes")
print("\n")

print("C4 using LDL")
Func_C4_strategy_1(n=10, maxIter=100, epsilon=10e-16, Print_Time="Yes", Print_Results="Yes")
print("\n")

print("C4 using Cholesky")
Func_C4_strategy_2(n=10, maxIter=100, epsilon=10e-16, Print_Time="Yes", Print_Results="Yes")

print("\n\nN = 50 \n")

print("C3")
Program_for_C3(n=50, Print_Time="Yes", Print_Results="Yes")
print("\n")

print("C4 using LDL")
Func_C4_strategy_1(n=50, maxIter=100, epsilon=10e-16, Print_Time="Yes", Print_Results="Yes")
print("\n")

print("C4 using Cholesky")
Func_C4_strategy_2(n=50, maxIter=100, epsilon=10e-16, Print_Time="Yes", Print_Results="Yes")


print("\n\nN = 100 \n")

print("C3")
Program_for_C3(n=100, Print_Time="Yes", Print_Results="Yes")
print("\n")

print("C4 using LDL")
Func_C4_strategy_1(n=100, maxIter=100, epsilon=10e-16, Print_Time="Yes", Print_Results="Yes")
print("\n")

print("C4 using Cholesky")
Func_C4_strategy_2(n=100, maxIter=100, epsilon=10e-16, Print_Time="Yes", Print_Results="Yes")


import numpy as np

def ReadMatrix(source, shape, symm=False):

    matrix = np.zeros(shape)

    with open(source, "r") as file:

        a = file.readlines()

    for line in a:

        row, column, value = line.strip().split()
        row = int(row)
        column = int(column)
        value = float(value)
        matrix[row - 1, column - 1] = value

        if symm == True:

            matrix[column - 1, row - 1] = value

    return matrix

# Function to read a vector from a file
def ReadVector(source, n):

    # Parameters:
    # source  Path to the input file containing the vector data
    #n The number of elements in the vector

    # Initialize an empty vector
    v = np.zeros(n)

    # Open the file containing the vector data
    with open(source, "r") as file:
        # Read all lines from the file
        lines = file.readlines()

    # Iterate over each line in the file
    for line in lines:
        # Split the line by spaces to extract the index and value
        idx, value = line.strip().split()

        # Convert the index to an integer (1-based to 0-based indexing)
        idx = int(idx)

        # Convert the value to a float
        value = float(value)

        # Fill the vector with the value at the specified index (idx-1 for 0-based indexing)
        v[idx - 1] = value

    # Return the populated vector
    return v



# Define the Matrix KKT
def M_KKT_C5(G, C, A, n, m, p, lamb,s):
    S = np.diag(s)
    Lambda = np.diag(lamb)
    temp1 = np.concatenate((G, -A, -C, np.zeros((n, m))),axis = 1)
    temp2 = np.concatenate((- np.transpose(A),np.zeros((p, p + 2 * m))), axis = 1)
    temp3 = np.concatenate((np.transpose(- C),np.zeros((m, p + m)), np.identity(m)), axis = 1)
    temp4 = np.concatenate((np.zeros((m, n + p)), S, Lambda), axis = 1)
    M = np.concatenate((temp1, temp2, temp3, temp4))

    return M, S, Lambda

def funC5(A, G, C, g, x, gamma, lamb, s, bm, d):

    comp1 = G.dot(x)+g-A.dot(gamma)-C.dot(lamb)
    comp2 = bm-np.transpose(A).dot(x)
    comp3 = s+d-np.transpose(C).dot(x)
    comp4 = s*lamb

    return np.concatenate((comp1,comp2,comp3,comp4))


def Function_C5(maxIter=100, epsilon=10e-16, Print_Time = "Yes", Print_Results = "No", Data = "optpr1-20241108"):

    np.random.seed(2)
    random.seed(2)

    n = int(np.loadtxt(Data + "/g.dad")[:,0][-1])
    p = n // 2
    m = 2 * n
    A = ReadMatrix(Data + "/A.dad", (n, p))
    bm = ReadVector(Data + "/b.dad", p)
    C = ReadMatrix(Data + "/C.dad", (n, m))
    d = ReadVector(Data + "/d.dad", m)
    e = np.ones((m))
    G = ReadMatrix(Data + "/g.dad", (n, n), True)
    g = np.zeros(n)
    x = np.zeros((n))
    gamma = np.ones((p))
    lamb = np.ones((m))
    s = np.ones((m))
    z = np.concatenate((x,gamma,lamb,s))

    if Print_Time == "Yes":
        np.random.seed(2)
        Start = time.time()

    # Get values from the function
    Mat, S, Lambda = M_KKT_C5(G, C, A, n, m, p, lamb, s)

    for i in range(maxIter):

        b = - funC5(A, G, C, g, x, gamma, lamb, s, bm, d)
        delta = np.linalg.solve(Mat, b)

        alpha = Newton_step(lamb,delta[(n + p) : (n + p + m)], s, delta[(n + m + p):])

        # Compute adjust parameters
        mu = s.dot(lamb) / m
        Mu = ((s + alpha * delta[(n + m + p):]).dot(lamb + alpha * delta[(n + p):(n + m + p)])) / m
        sigma = (Mu / mu) ** 3

        # Adjust substep
        b[(n + m + p):] = b[(n + p + m):] - np.diag(delta[(n + p + m):] * delta[(n + p) : (n + p + m)]).dot(e) + sigma * mu * e
        delta = np.linalg.solve(Mat, b)

        # Step-size adjust substep
        alpha = Newton_step(lamb, delta[(n + p):(n + p + m)], s, delta[(n + m + p):])
        z = z + 0.95 * alpha * delta

        # Stopping criteria
        if (np.linalg.norm(- b[:n]) < epsilon) or (np.linalg.norm(- b[n:(n + m)]) < epsilon) or (np.linalg.norm(- b[(n + p):(n + p + m)]) < epsilon) or (np.abs(mu) < epsilon):

            break

        # Update the Matrix KKT
        x = z[:n]
        gamma = z[n:(n+p)]
        lamb = z[(n + p):(n + m + p)]
        s = z[(n + m + p):]
        Mat, S, Lambda = M_KKT_C5(G, C, A, n, m, p, lamb,s)

    condition_number = np.linalg.cond(Mat)

    if Print_Time == "Yes":

        End = time.time()

        if Print_Results == "Yes":

            print("Computation time: ",End - Start)

    if Print_Results == "Yes":

        print('Minimum found:', F(x, G, g))
        print('Condition number:', condition_number)
        print('Iterations:', i)


print("\nResults For optpr1:\n")

Function_C5(maxIter=100, epsilon=10e-16, Print_Time = "Yes", Print_Results = "Yes", Data = r"optpr1-20241108")
print("\nResults For optpr2:\n ")
Function_C5(maxIter=100, epsilon=10e-16, Print_Time = "Yes", Print_Results = "Yes", Data = r"optpr2-20241108")



# Define the Matrix KKT
def M_KKT_C6(G, C, A, n, m, p, lamb,s):

    S = np.diag(s)
    Lambda = np.diag(lamb)
    temp1 = np.concatenate((G,- A, - C),axis = 1)
    temp2 = np.concatenate((- np.transpose(A), np.zeros((p, p + m))), axis = 1)
    temp3 = np.concatenate((- np.transpose(C), np.zeros((m, p)), np.diag(-1 / lamb * s)), axis = 1)
    Mat = np.concatenate((temp1, temp2, temp3))

    return Mat, S, Lambda

def Function_C6(maxIter=100, epsilon=10e-16, Print_Time = "Yes", Print_Results = "No", Data = "optpr1-20241108"):
    np.random.seed(2)
    random.seed(2)

    n = int(np.loadtxt(Data + "/g.dad")[:,0][-1])
    p = n // 2
    m = 2 * n
    A = ReadMatrix(Data + "/A.dad", (n, p))
    bm = ReadVector(Data + "/b.dad", p)
    C = ReadMatrix(Data + "/C.dad", (n, m))
    d = ReadVector(Data + "/d.dad", m)
    e = np.ones((m))
    G = ReadMatrix(Data + "/g.dad", (n, n), True)
    g = np.zeros((n))
    x = np.zeros((n))
    gamma = np.ones((p))
    lamb = np.ones((m))
    s = np.ones((m))
    z = np.concatenate((x, gamma, lamb, s))

    if Print_Time == "Yes":
        np.random.seed(2)
        Start = time.time()

    # Get values from the function
    Mat,S,Lamb = M_KKT_C6(G, C, A, n, m, p, lamb,s)

    for i in range(maxIter):
        lamb_inv = np.diag(1/lamb)
        b = funC5(A, G, C, g, x, gamma, lamb, s, bm, d)
        r1, r2, r3, r4 = b[:n], b[n:n+p], b[n+p:n+p+m], b[n+p+m:]
        b = np.concatenate(([-r1,-r2,-r3+1/lamb*r4]))

        # Use LDL factorization
        L, D, perm = ldl(Mat)
        y = np.linalg.solve(L, b)
        delta = np.linalg.solve(D.dot(np.transpose(L)), y)
        deltaS = lamb_inv.dot(- r4 - s * delta[(n + p):])
        delta = np.concatenate((delta, deltaS))


        alpha = Newton_step(lamb,delta[(n + p) : (n + p + m)], s, delta[(n + m + p):])

        # Get the adjusted parameters
        mu = s.dot(lamb) / m
        Mu = ((s + alpha * delta[(n + m + p):]).dot(lamb + alpha * delta[(n + p):(n + m + p)])) / m
        sigma = (Mu / mu) ** 3

        Ds = np.diag(delta[(n + p + m):] * delta[(n + p):(n + p + m)])
        b = np.concatenate((- r1, - r2, - r3 + lamb_inv.dot(r4 + Ds.dot(e) - sigma * mu * e)))

        # LDL factorization second time
        y = np.linalg.solve(L, b)
        delta = np.linalg.solve(D.dot(np.transpose(L)), y)
        deltaS = lamb_inv.dot(- r4 - Ds.dot(e) + sigma * mu * e - s * delta[(n + p):])
        delta = np.concatenate((delta, deltaS))

        alpha = Newton_step(lamb, delta[(n + p):(n + p + m)], s, delta[(n + m + p):])

        # Update the substep
        z = z + 0.95 * alpha * delta

        if (np.linalg.norm(- b[:n]) < epsilon) or (np.linalg.norm(- b[n:(n + m)]) < epsilon) or (np.linalg.norm(- b[(n + p):(n + p + m)]) < epsilon) or (np.abs(mu) < epsilon):

            break

        # Update Matrix KKT
        x = z[:n]
        gamma = z[n:(n+p)]
        lamb = z[(n + p):(n + m + p)]
        s = z[(n + m + p):]
        Mat,Lamb,S = M_KKT_C6(G, C, A, n, m, p, lamb,s)

    condition_number = np.linalg.cond(Mat)

    if Print_Time == "Yes":

        End = time.time()

        if Print_Results == "Yes":

            print("Computation time: ",End - Start)

    if Print_Results == "Yes":

        print('Minimum is:', F(x, G, g))
        print('Condition number:', condition_number)
        print('Iterations needed:', i)


print("\nResults For optpr1:\n")

Function_C6(maxIter=100, epsilon=10e-16, Print_Time = "Yes", Print_Results = "Yes", Data = "optpr1-20241108")
print("\nResults For optp2:\n")

Function_C6(maxIter=100, epsilon=10e-16, Print_Time = "Yes", Print_Results = "Yes", Data = "optpr2-20241108")